const tracks = [
    {
      id: 1,
      title: "Guilt",
      titleSpan: "",
      author: "Nero",
      album: "Welcome Reality",
      time: "",
    },
    {
      id: 2,
      title: 'Elektro',
      titleSpan: '',
      author: 'Dynoro, Outwork, Mr. Gee',
      album: 'Elektro',
      time: '2:22',
    },
    {
      id: 3,
      title: 'I’m Fire',
      titleSpan: '',
      author: 'Ali Bakgor',
      album: 'I’m Fire',
      time: '2:22',
    },
    {
      id: 4,
      title: 'Non Stop',
      titleSpan: '(Remix)',
      author: 'Стоункат, Psychopath',
      album: 'Non Stop',
      time: '4:12',
    },
    {
      id: 5,
      title: 'Run Run',
      titleSpan: '(feat. AR/CO)',
      author: 'Jaded, Will Clarke, AR/CO',
      album: 'Run Run',
      time: '2:54',
    },
    {
      id: 6,
      title: 'Eyes on Fire',
      titleSpan: '(Zeds Dead Remix)',
      author: 'Blue Foundation, Zeds Dead',
      album: 'Eyes on Fire',
      time: '5:20',
    },
    {
      id: 7,
      title: 'Mucho Bien',
      titleSpan: '(Hi Profile Remix)',
      author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
      album: 'Mucho Bien',
      time: '3:41',
    },
    {
      id: 8,
      title: 'Knives n Cherries',
      titleSpan: '',
      author: 'minthaze',
      album: 'Captivating',
      time: '1:48',
    },
    {
      id: 9,
      title: 'How Deep Is Your Love',
      titleSpan: '',
      author: 'Calvin Harris, Disciples',
      album: 'How Deep Is Your Love',
      time: '3:32',
    },
    {
      id: 10,
      title: 'Morena',
      titleSpan: '',
      author: 'Tom Boxer',
      album: 'Soundz Made in Romania',
      time: '3:36',
    },
    {
      id: 11,
      title: '',
      titleSpan: '',
      author: '',
      album: '',
      time: '',
    },
]

export default tracks